### ISSUE TITLE
TestAccGitLabProjectApprovalRule_basic test failing in master

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#533]
The TestAccGitLabProjectApprovalRule_basic failed after merging #525 

Action: https://github.com/gitlabhq/terraform-provider-gitlab/runs/1779107460

Error:

```
2021-01-27T19:00:30.9669258Z -----------------------------------------------------
2021-01-27T19:00:30.9678567Z ##[error]    testing.go:745: Error destroying resource! WARNING: Dangling resources
2021-01-27T19:00:30.9691106Z         may exist. The full state and error is shown below.
2021-01-27T19:00:30.9691620Z         
2021-01-27T19:00:30.9692202Z         Error: Check failed: User still exists
2021-01-27T19:00:30.9692654Z         
2021-01-27T19:00:30.9693034Z         State: <no state>
2021-01-27T19:00:30.9694226Z --- FAIL: TestAccGitLabProjectApprovalRule_basic (12.96s)
```

**Comment by armsnyder** [comment]
It's a flakey test
