### PR TITLE
Check for state change on user delete

### LINKED ISSUE #533: TestAccGitLabProjectApprovalRule_basic test failing in master
The TestAccGitLabProjectApprovalRule_basic failed after merging #525 

Action: https://github.com/gitlabhq/terraform-provider-gitlab/runs/1779107460

Error:

```
2021-01-27T19:00:30.9669258Z -----------------------------------------------------
2021-01-27T19:00:30.9678567Z ##[error]    testing.go:745: Error destroying resource! WARNING: Dangling resources
2021-01-27T19:00:30.9691106Z         may exist. The full state and error is shown below.
2021-01-27T19:00:30.9691620Z         
2021-01-27T19:00:30.9692202Z         Error: Check failed: User still exists
2021-01-27T19:00:30.9692654Z         
2021-01-27T19:00:30.9693034Z         State: <no state>
2021-01-27T19:00:30.9694226Z --- FAIL: TestAccGitLabProjectApprovalRule_basic (12.96s)
```

### PR DESCRIPTION
**Pull request by armsnyder**
Fixes #533 

I analyzed the test debug output and found that the problem was some inconsistency after a user is deleted.

I see `DELETE /api/v4/users/114 HTTP/1.1` return `HTTP/1.1 204 No Content`, and then later in the test during the destroy check, `GET /api/v4/users/114 HTTP/1.1` returns `HTTP/1.1 200 OK`.

This fix adds `WaitForState` to the `gitlab_user` delete function.

### CODE REVIEW

File: gitlab/resource_gitlab_user.go [hunk 1]
```diff
@@ -2,8 +2,10 @@ package gitlab
 
 import (
 	"fmt"
+	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
```
Comment (roidelapluie) [inline gitlab/resource_gitlab_user.go:5]: please reorder

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
LGTM, one nit

File: gitlab/resource_gitlab_user.go (hunk 1 above)
Comment (armsnyder) [reply gitlab/resource_gitlab_user.go]: done. we should consider golangci-lint since it can check for organized imports. #361
