### PR TITLE
TestAccGitLabProjectApprovalRule_basic test failure

### LINKED ISSUE #494: TestAccGitLabProjectApprovalRule_basic test failure
The `TestAccGitLabProjectApprovalRule_basic` acceptance test is failing. It was introduced in #250 but we didn't catch it due to #493.

Partial log:

```
2020-11-24T09:43:11.9256854Z ##[error]    testing.go:745: Error destroying resource! WARNING: Dangling resources
2020-11-24T09:43:11.9268233Z         may exist. The full state and error is shown below.
2020-11-24T09:43:11.9268798Z         
2020-11-24T09:43:11.9269286Z         Error: Check failed: User still exists
2020-11-24T09:43:11.9269753Z         
2020-11-24T09:43:11.9270368Z         State: <no state>
2020-11-24T09:43:11.9271577Z --- FAIL: TestAccGitLabProjectApprovalRule_basic (11.62s)
```

Full log: https://github.com/gitlabhq/terraform-provider-gitlab/runs/1446853398

### PR DESCRIPTION
**Pull request by cnuss**
I think there's a logic bug here.

Also adding some logging for context

fixes #494

### CODE REVIEW

**Comment by armsnyder** [comment]
Thanks for the stab at this issue. The original logic of `testAccCheckGitlabUserDestroy ` looks correct to me, however.

**Comment by cnuss** [comment]
Yea basically getting a PR in place so I can see acceptance test output. Now I'm being lazy so I don't have to try and run them locally.

@armsnyder quick question, why is https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/.github/workflows/acceptance-tests.yml#L35 set? 

This means that initial PRs won't get acceptance test runs, but subsequent pushes will. Can I remove it?

**Comment by cnuss** [comment]
> This means that initial PRs won't get acceptance EE test runs, but subsequent pushes will. Can I remove it?

Oh never mind, appears so this is so EE acceptance tests don't attempt to run in forked repositories, but do run when something is merged to the project

**Comment by cnuss** [comment]
CE tests pass, I think my theory is that EE users delete differently than CE.

**Comment by cnuss** [comment]
Blocked by unable to run EE tests
