### ISSUE TITLE
TestAccGitLabProjectApprovalRule_basic test failure

### ISSUE THREAD

**Issue by armsnyder** [gitlabhq/terraform-provider-gitlab#494]
The `TestAccGitLabProjectApprovalRule_basic` acceptance test is failing. It was introduced in #250 but we didn't catch it due to #493.

Partial log:

```
2020-11-24T09:43:11.9256854Z ##[error]    testing.go:745: Error destroying resource! WARNING: Dangling resources
2020-11-24T09:43:11.9268233Z         may exist. The full state and error is shown below.
2020-11-24T09:43:11.9268798Z         
2020-11-24T09:43:11.9269286Z         Error: Check failed: User still exists
2020-11-24T09:43:11.9269753Z         
2020-11-24T09:43:11.9270368Z         State: <no state>
2020-11-24T09:43:11.9271577Z --- FAIL: TestAccGitLabProjectApprovalRule_basic (11.62s)
```

Full log: https://github.com/gitlabhq/terraform-provider-gitlab/runs/1446853398

**Comment by nicholasklick** [comment]
@btyy77c mind taking a look at this?

**Comment by nicholasklick** [comment]
Actually @armsnyder this appears resolved in the latest run?

```
2020-11-30T05:31:05.5426370Z === RUN   TestAccGitLabProjectApprovalRule_basic
2020-11-30T05:31:17.1621315Z --- PASS: TestAccGitLabProjectApprovalRule_basic (11.62s)
```

**Comment by nicholasklick** [comment]
Also looks good here https://github.com/gitlabhq/terraform-provider-gitlab/actions/runs/390938808

I say we close this?

**Comment by armsnyder** [comment]
All good then!
